dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose -f local.yml build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose -f local.yml run --rm django python manage.py migrate
        - docker-compose -f local.yml up -d
      script:
      # no test actually comment this for now
      # - "docker-compose -f local.yml run django pytest"
        - "docker-compose -f local.yml run django mypy nobinobi"
      #  - "docker-compose -f local.yml run django coverage run -m pytest"
      #  - "docker-compose -f local.yml run django coverage html"
      after_failure:
        - docker-compose -f local.yml logs
      after_success:
        - "docker-compose -f local.yml run django codecov"

